image:
  file: Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
tasks:
  - init: |
      eval $(command gp env -e)
      synapse -u "$SYN_USER" -p "$SYN_TOKEN" \
        get -r syn25685780 --downloadLocation /workspace/testdata && \
        cp /workspace/cylinter/cylinter/config.yml /workspace/testdata
    command: cylinter /workspace/testdata/config.yml
  
